// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SafariApi;

namespace SafariApi.Migrations
{
    [DbContext(typeof(SeenAnimalsContext))]
    [Migration("20181103192637_AddedAnimalsAndData")]
    partial class AddedAnimalsAndData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SafariApi.Models.SeenAnimals", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CountOfTimesSeen");

                    b.Property<string>("LocationOfLastSeen");

                    b.Property<string>("Species");

                    b.HasKey("Id");

                    b.ToTable("SeenAnimals");

                    b.HasData(
                        new { Id = -1, CountOfTimesSeen = 1, LocationOfLastSeen = "Field", Species = "Lion" },
                        new { Id = -2, CountOfTimesSeen = 8, LocationOfLastSeen = "Field", Species = "Zebra" },
                        new { Id = -3, CountOfTimesSeen = 7, LocationOfLastSeen = "Lake", Species = "Elephant" },
                        new { Id = -4, CountOfTimesSeen = 42, LocationOfLastSeen = "Cavern", Species = "Hyena" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
